name: Build and release
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: imstar15/github-changelog-action@v1.0.1
        with:
          next_version: "1.0.1"
